"""
HTML reporter — human-readable scan report with severity-coloured findings table.

Generates a self-contained HTML file that requires no external assets.
Suitable for attaching to GRC tickets or emailing to security stakeholders.
"""

from __future__ import annotations

from pathlib import Path
from argus.core.session import SessionState, Finding

_SEVERITY_COLOUR = {
    "Critical": "#f85149",
    "High":     "#f0883e",
    "Medium":   "#e3b341",
    "Low":      "#58a6ff",
    "None":     "#6e7681",
    "Unknown":  "#6e7681",
}

_CSS = """
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
       background:#0d1117;color:#c9d1d9;margin:0;padding:2rem;}
  h1{color:#f0883e;font-size:1.6rem;margin-bottom:.25rem;}
  .meta{color:#8b949e;font-size:.85rem;margin-bottom:2rem;}
  .stats{display:flex;gap:2rem;margin-bottom:2rem;flex-wrap:wrap;}
  .stat{background:#161b22;border:1px solid #21262d;border-radius:8px;
        padding:1rem 1.5rem;text-align:center;}
  .stat-n{font-size:2rem;font-weight:800;color:#f0883e;line-height:1;}
  .stat-l{font-size:.75rem;color:#8b949e;margin-top:.25rem;}
  table{width:100%;border-collapse:collapse;font-size:.85rem;}
  th{text-align:left;padding:.6rem 1rem;color:#8b949e;font-size:.75rem;
     text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid #21262d;}
  td{padding:.65rem 1rem;border-bottom:1px solid #21262d;vertical-align:top;}
  tr:hover td{background:rgba(255,255,255,.02);}
  .sev{font-weight:700;font-size:.8rem;}
  .tag{display:inline-block;font-size:.7rem;padding:.1rem .45rem;
       border-radius:4px;background:#21262d;color:#8b949e;margin:.1rem;}
  .vec{font-family:'SF Mono','Fira Code',monospace;font-size:.72rem;color:#58a6ff;}
  footer{margin-top:2rem;color:#6e7681;font-size:.8rem;}
</style>
"""


def _sev_html(severity: str) -> str:
    colour = _SEVERITY_COLOUR.get(severity, "#6e7681")
    return f'<span class="sev" style="color:{colour}">{severity}</span>'


def _finding_row(f: Finding) -> str:
    tags = "".join(f'<span class="tag">{t}</span>' for t in f.compliance_tags[:4])
    return (
        f"<tr>"
        f"<td>{f.finding_id}</td>"
        f"<td>{f.owasp_category}</td>"
        f"<td>{f.surface}</td>"
        f"<td>{f.strategy}</td>"
        f"<td>{_sev_html(f.cvss_severity)}</td>"
        f"<td>{f.cvss_base_score:.1f}</td>"
        f"<td><span class='vec'>{f.cvss_vector}</span></td>"
        f"<td>{tags}</td>"
        f"</tr>"
    )


class HTMLReporter:
    def generate(self, session: SessionState, output_path: str | None = None) -> str:
        s = session.summary()
        confirmed = session.confirmed_findings()

        rows = "".join(_finding_row(f) for f in confirmed) or (
            "<tr><td colspan='8' style='color:#6e7681;text-align:center;'>"
            "No confirmed findings</td></tr>"
        )

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>ARGUS Report — {s['session_id']}</title>
  {_CSS}
</head>
<body>
  <h1>ARGUS Scan Report</h1>
  <div class="meta">
    Session: {s['session_id']} &nbsp;|&nbsp;
    Profile: {s['phase']} &nbsp;|&nbsp;
    Payloads sent: {s['payloads_sent']} &nbsp;|&nbsp;
    Started: {s['started_at']}
  </div>

  <div class="stats">
    <div class="stat">
      <div class="stat-n" style="color:#f85149">{s['critical']}</div>
      <div class="stat-l">Critical</div>
    </div>
    <div class="stat">
      <div class="stat-n" style="color:#f0883e">{s['high']}</div>
      <div class="stat-l">High</div>
    </div>
    <div class="stat">
      <div class="stat-n" style="color:#e3b341">{s['medium']}</div>
      <div class="stat-l">Medium</div>
    </div>
    <div class="stat">
      <div class="stat-n" style="color:#58a6ff">{s['low']}</div>
      <div class="stat-l">Low</div>
    </div>
    <div class="stat">
      <div class="stat-n">{s['total_findings']}</div>
      <div class="stat-l">Total findings</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>ID</th><th>OWASP</th><th>Surface</th><th>Strategy</th>
        <th>Severity</th><th>CVSS</th><th>Vector</th><th>Compliance</th>
      </tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>

  <footer>
    Generated by <a href="https://github.com/sunilgentyala/argus" style="color:#58a6ff;">
    ARGUS v1.1.0</a> — for authorized security testing only.
  </footer>
</body>
</html>"""

        if output_path:
            Path(output_path).write_text(html, encoding="utf-8")
        return html
